---
- name: Pull Docker Image and Run Container
  hosts: localhost
  remote_user: sam
  become: false
  tasks:
    - name: Pull Docker Image from Docker Hub
      docker_image:
        name: "sampath333/test"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
        
    - name: Start Docker Service
      service:
        name: docker
        state: started

    - name: Run scientific_calculator Container
      shell: docker run -it -d --name scientific_calculator sampath333/test /bin/bash